#on:
#  push:
#    branches:
#      - master
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - run: echo "🎉 The job was automatically triggered by a ${{ GITHUB_WORKSPACE }} event."


name: GitHub Actions Demo
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.workspace }} event."
