name: GitHub Actions Demo
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-java@v4.2.2
        name: Setup Java JDK
        with:
          version: '17'
          distribution: 'oracle'

