name: GitHub Actions Demo
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - run: echo ${{ github.workspace }}
#      - uses: actions/setup-java@v4.2.2
#        with:
#          distribution: 'oracle'
#          java-version: 17
      - run: mvn clean install
