name: GitHub Actions Demo
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
        name: Set up JDK 11
      - uses: actions/setup-java@v4.2.2
        with:
          java-version: 17
      - run: mvn clean install
